{
 "title": "Main Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Average amount of requests per second",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rate(traffic_count_total[1m])" }
   ]
  },
  {
   "title": "Total traffic count (amount of requests in the last minute)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(traffic_count_total[1m])"
    }
   ]
  },
  {
   "title": "Error rate (across all the requests)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rate(error_count_total[1m])" }
   ]
  },
  {
   "title": "Latency (seconds)",
   "type": "histogram",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(latency_histogram_count[1m])"
    }
   ]
  }
 ]
}