{
 "title": "ML Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Training data label distribution",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "training_counter_total{observed_class=\"0\"}",
     "legendFormat": "No Churn Counts"
    },
    {
     "expr": "training_counter_total{observed_class=\"1\"}",
     "legendFormat": "Churn Counts"
    }
   ]
  },
  {
   "title": "ML Model Accuracy (Percent)",
   "type": "gauge",
   "description": "Model Accuracy by taking into account prediction labels and real feedback",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "query_result_accuracy_model * 100"
    }
   ]
  },
  {
   "title": "Prediction Label distribution",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(prediction_counter_total{predicted_class=\"0\"}[$__range])",
     "legendFormat": "No Churn Counts"
    },
    {
     "expr": "increase(prediction_counter_total{predicted_class=\"1\"}[$__range])",
     "legendFormat": "Churn Counts"
    }
   ]
  },
  {
   "title": "ML Model Accuracy Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "query_result_accuracy_model" }
   ]
  }
 ]
}